#Prometheus.yml para Keycloak http
global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: "keycloak-metrics"
    static_configs:
      - targets: ["keycloak:9000"]
    metrics_path: /management/metrics
    scheme: http # Garante que o Prometheus use HTTP

  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]
